// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllBoards() {
  return window['go']['main']['App']['GetAllBoards']();
}

export function WriteBoard(arg1) {
  return window['go']['main']['App']['WriteBoard'](arg1);
}
