// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllBoards():Promise<string>;

export function WriteBoard(arg1:Array<main.Board>):Promise<boolean>;
